import { picking } from "./gettingRecipeName";
import { getRecipe } from "./recipeSearch-fetch.js";

export function ModalRendering({ mealprep }) {
  return (
    <>
      <h1 id="modal-head">Recipe Name:</h1>
      {mealprep.meal}
      <p>Category:</p>
      {mealprep.category}
      <p>Type:</p>
      {mealprep.type}
      <img src={mealprep.photo} />
      <img src={mealprep.video} />
      <h2>steps</h2>
      {mealprep.instructions}
      <ul>
        <ul>
          Ingridient:
          {mealprep.ingredient1}
          <li>Measurement:</li>
        </ul>
        <ul>Ingridient:</ul>
        {mealprep.ingredient1}
        <li>Measurement:</li>
        {mealprep.strMeasure1}
        <ul>Ingridient:</ul>
        {mealprep.ingredient2}
        <li>Measurement:</li>
        {mealprep.strMeasure2}
        <ul>Ingridient:</ul>
        {mealprep.ingredient3}
        <li>Measurement:</li>
        {mealprep.strMeasure3}
        <ul>Ingridient:</ul>
        {mealprep.ingredient4}
        <li>Measurement:</li>
        {mealprep.strMeasure4}
        <ul>Ingridient:</ul>
        {mealprep.ingredient5}
        <li>Measurement:</li>
        {mealprep.strMeasure5}
        <ul>Ingridient:</ul>
        {mealprep.ingredient6}
        <li>Measurement:</li>
        {mealprep.strMeasure6}
        <ul>Ingridient:</ul>
        {mealprep.ingredient7}
        <li>Measurement:</li>
        {mealprep.strMeasure7}
        <ul>Ingridient:</ul>
        {mealprep.ingredient8}
        <li>Measurement:</li>
        {mealprep.strMeasure8}
        <ul>Ingridient:</ul>
        {mealprep.ingredient9}
        <li>Measurement:</li>
        {mealprep.strMeasure9}
        <ul>Ingridient:</ul>
        {mealprep.ingredient10}
        <li>Measurement:</li>
        {mealprep.strMeasure10}
        <ul>Ingridient:</ul>
        {mealprep.ingredient11}
        <li>Measurement:</li>
        {mealprep.strMeasure11}
        <ul>Ingridient:</ul>
        {mealprep.ingredient12}
        <li>Measurement:</li>
        {mealprep.strMeasure12}
        <ul>Ingridient:</ul>
        {mealprep.ingredient13}
        <li>Measurement:</li>
        {mealprep.strMeasure13}
        <ul>Ingridient:</ul>
        {mealprep.ingredient14}
        <li>Measurement:</li>
        {mealprep.strMeasure14}
        <ul>Ingridient:</ul>
        {mealprep.ingredient15}
        <li>Measurement:</li>
        {mealprep.strMeasure15}
        <ul>Ingridient:</ul>
        {mealprep.ingredient16}
        <li>Measurement:</li>
        {mealprep.strMeasure16}
        <ul>Ingridient:</ul>
        {mealprep.ingredient17}
        <li>Measurement:</li>
        {mealprep.strMeasure17}
        <ul>Ingridient:</ul>
        {mealprep.ingredient18}
        <li>Measurement:</li>
        {mealprep.strMeasure18}
        <ul>Ingridient:</ul>
        {mealprep.ingredient19}
        <li>Measurement:</li>
        {mealprep.strMeasure19}
        <ul>Ingridient:</ul>
        {mealprep.ingredient20}
        <li>Measurement:</li>
        {mealprep.strMeasure20}
      </ul>
    </>
  );
}
